version: "3.9"
   
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --no-input &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - staticfiles:/app/static/
    network_mode: "host"
    expose:
      - 8000
    restart: "on-failure"

  nginx:
    build:
      context: .
      dockerfile: config/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - staticfiles:/app/static/
    depends_on:
      - web
    restart: "on-failure"

volumes:
  staticfiles:

