# Generated by Django 3.2.4 on 2021-06-27 09:47

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=255, unique=True)),
                ('displayName', models.CharField(max_length=255)),
                ('fieldType', models.CharField(blank=True, max_length=64)),
                ('isRequired', models.BooleanField(default=False)),
                ('isMultiselect', models.BooleanField(default=False)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='AttributeInProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('attribute', models.ForeignKey(db_column='attributeId', on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
            ],
            options={
                'db_table': 'attribute_in_product',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=128, unique=True)),
                ('catImg', models.ImageField(upload_to='')),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_created_by', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('searchTags', models.TextField(blank=True, null=True)),
                ('mrp', models.PositiveIntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('attributs', models.ManyToManyField(through='product.AttributeInProduct', to='product.Attribute')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SubCategoryName', models.CharField(max_length=128, unique=True)),
                ('subCatImg', models.ImageField(upload_to='')),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('category', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('createdBy', models.ForeignKey(db_column='createdById', on_delete=django.db.models.deletion.CASCADE, related_name='subcat_created_by', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(db_column='updatedById', on_delete=django.db.models.deletion.CASCADE, related_name='subcat_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verticalName', models.CharField(max_length=128, unique=True)),
                ('verticalImg', models.ImageField(upload_to='')),
                ('isActive', models.BooleanField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('createdBy', models.ForeignKey(db_column='createdById', on_delete=django.db.models.deletion.CASCADE, related_name='vartical_created_by', to=settings.AUTH_USER_MODEL)),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
                ('updatedBy', models.ForeignKey(db_column='updatedById', on_delete=django.db.models.deletion.CASCADE, related_name='vartical_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vertical',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('isMain', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='product.vertical'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='createdBy',
            field=models.ForeignKey(db_column='createdById', on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(db_column='subCategoryId', on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='updatedBy',
            field=models.ForeignKey(db_column='updatedById', on_delete=django.db.models.deletion.CASCADE, related_name='product_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='vertical',
            field=models.ForeignKey(db_column='verticalId', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.vertical'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=128)),
                ('state', models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, to='product.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=128, unique=True)),
                ('brandImg', models.ImageField(blank=True, null=True, upload_to='')),
                ('isActive', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brandRating', models.FloatField(default=0.0)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('createdBy', models.ForeignKey(db_column='createdById', on_delete=django.db.models.deletion.CASCADE, related_name='brand_created_by', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(db_column='updatedById', on_delete=django.db.models.deletion.CASCADE, related_name='brand_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.AddField(
            model_name='attributeinproduct',
            name='product',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='vertical',
            field=models.ForeignKey(db_column='verticalId', on_delete=django.db.models.deletion.CASCADE, to='product.vertical'),
        ),
    ]
