# Generated by Django 3.2.4 on 2021-06-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='SubCategoryName',
            new_name='subCategoryName',
        ),
    ]
