# Generated by Django 3.2.4 on 2021-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_vertical_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandImg',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='catImg',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCatImg',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vertical',
            name='verticalImg',
            field=models.FileField(upload_to=''),
        ),
    ]
