# Generated by Django 3.2.4 on 2021-07-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210731_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandImg',
            field=models.FileField(blank=True, null=True, upload_to='product/brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catImg',
            field=models.FileField(upload_to='product/category'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/product'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCatImg',
            field=models.FileField(upload_to='product/subcategory'),
        ),
        migrations.AlterField(
            model_name='vertical',
            name='verticalImg',
            field=models.FileField(upload_to='product/vertical'),
        ),
    ]
