# Generated by Django 3.2.4 on 2021-08-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210731_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parentVerticalId', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(db_column='BrandId', on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='product.brand'),
        ),
    ]
