# Generated by Django 3.2.4 on 2021-09-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_attributesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='sectionType',
            field=models.ForeignKey(db_column='sectionTypeId', default=1, on_delete=django.db.models.deletion.CASCADE, to='product.attributesection'),
            preserve_default=False,
        ),
    ]
