# Generated by Django 3.2.4 on 2021-09-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_attribute_sectiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='vertical',
            field=models.ForeignKey(blank=True, db_column='verticalId', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.vertical'),
        ),
    ]
