# Generated by Django 3.2.4 on 2021-09-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_brand_vertical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='vertical',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brandRating',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='vertical',
        ),
        migrations.CreateModel(
            name='BrandInVertical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=True)),
                ('brandRating', models.FloatField(default=0.0)),
                ('vertical', models.ForeignKey(db_column='verticalId', on_delete=django.db.models.deletion.CASCADE, to='product.vertical')),
            ],
            options={
                'db_table': 'brand_in_vertical',
            },
        ),
        migrations.CreateModel(
            name='AttributeInVertical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(db_column='attributeId', on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
                ('vertical', models.ForeignKey(db_column='verticalId', on_delete=django.db.models.deletion.CASCADE, to='product.vertical')),
            ],
            options={
                'db_table': 'attribute_in_vertical',
            },
        ),
    ]
