# Generated by Django 3.2.4 on 2021-07-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_account_type',
            field=models.CharField(choices=[('1', 'facebook'), ('2', 'google')], max_length=2),
        ),
    ]
