# Generated by Django 3.2.4 on 2021-07-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_mail_verify',
            new_name='is_mail_verified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_mobile_verify',
            new_name='is_mobile_verified',
        ),
    ]
